# Generated by Django 3.2.9 on 2021-12-06 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Acne Studios', 'Acne Studios'), ('Alexander McQueen', 'Alexander McQueen'), ('Balenciaga', 'Balenciaga'), ('Balmain', 'Balmain'), ('Bottega Veneta', 'Bottega Veneta'), ('Celine', 'Celine'), ('Chanel', 'Chanel'), ('Coach', 'Coach'), ('Dior', 'Dior'), ('Fendi', 'Fendi'), ('Givenchy', 'Givenchy'), ('Gucci', 'Gucci'), ('Hermes', 'Hermes'), ('Jacquemes', 'Jacquemes'), ('Louis Vuitton', 'Louis Vuitton'), ('Prada', 'Prada'), ('Saint Laurent', 'Saint Laurent'), ('Tom Ford', 'Tom Ford'), ('Valentino', 'Valentino'), ('Versace', 'Versace')], default='Acne Studios', max_length=20)),
                ('description', models.TextField(max_length=550)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Fair', 'Fair Wear and Tear'), ('Tlc', 'Major Tlc Needed')], default='New', max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.CharField(max_length=300)),
                ('image_2', models.CharField(max_length=300)),
                ('image_3', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
