# Generated by Django 3.2.9 on 2021-12-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_3',
            new_name='image3',
        ),
    ]
